### ISSUE TITLE
v2 Gene page not working for CCDC39 in lof curation portal

### ISSUE THREAD

**Issue by carmenglaze1** [broadinstitute/variant-curation-portal#281]
In the lof curation portal, for the project named "CCDC39_v4", the tab to click to the gnomAD v2 gene page isn't working. There is an error that says "gene not found". This is only an issue for CCDC39 and not other genes/projects. I can still see the v2 gene page for this gene if I access gnomAD v2 outside of the portal. Attached are screenshots of the error page that I get through the portal and what the v2 gene page looks like on the regular gnomAD browser.

![Screenshot 2024-05-09 121507](https://github.com/broadinstitute/variant-curation-portal/assets/146103822/daa512d7-d5ec-4382-a039-3d026a6da927)

![Screenshot 2024-05-09 121525](https://github.com/broadinstitute/variant-curation-portal/assets/146103822/98554ca6-0084-42a6-86ca-1f9b3cf83f14)

**Comment by rileyhgrant** [comment]
Heya @carmenglaze1,

Thanks for filing an issue on GitHub, it's much appreciated. Looks like there are two ENSG_IDs for this gene, and the one we used to make this variant portal is one that for some reason works on gnomAD v2, but not on v4.

Options are to remake the portal (not ideal if you're already midway/done curating the variants) and/or to look at why the browser behaves inconsistently. I'll plan on following up next week with you.

**Comment by carmenglaze1** [comment]
Hi!

Sorry for the late response. I'm not sure if you've looked into this at all
yet but the curation team talked about it more and we think it's okay to
just manually go to the gnomAD browser to find what we need in v2 without
going through the portal for this gene only. Thank you for checking in
though!

Best,
Carmen

**Comment by rileyhgrant** [comment]
> Hi! Sorry for the late response. I'm not sure if you've looked into this at all yet but the curation team talked about it more and we think it's okay to just manually go to the gnomAD browser to find what we need in v2 without going through the portal for this gene only. Thank you for checking in though! Best, Carmen


Sounds good.

Apologies also for my super late response to your problem, glad you found a workaround, even if it was less than ideal.
